"use strict";
exports.__esModule = true;
var retosRepaso2_1 = require("../retosRepaso2");
var Nokia3210 = new retosRepaso2_1.Mobile("Nokia", "3210", "Nokia Corporation, Finland", "microSD", "azul/gris", false, 0, 23);
var iPhone3G = new retosRepaso2_1.Mobile("iPhone", "3G", "Apple Inc", "microSD", "black", false, 1, 60);
var SamsugGalaxy10 = new retosRepaso2_1.Mobile("Samsug", "Galaxy 10", "SAMSUNG", "microSD", "black", true, 2, 358);
console.log(Nokia3210, iPhone3G, SamsugGalaxy10);
Nokia3210.is5G = true;
Nokia3210.cameraNumber = 4;
console.log(Nokia3210);
console.log(Object.keys(Nokia3210));
